# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Climate Knowledge Nepal deploy
"on":
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Installing App
        run: cd site && npm ci
      - name: Building App
        run: |
          cd site
          npm install
          npm run build
          npm run export
          touch ./out/.nojekyll
        env:
          NEXT_PUBLIC_PAT: "${{ secrets.NEXT_PUBLIC_PAT }}"
      - name: "Deploy"
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: "${{ secrets.ACCESS_TOKEN }}"
          branch: gh-pages
          folder: site/out
